server:
  port: 8000
spring:
  application:
    name: eureka_center
  security:
    user:
      name: eureka
      password: 123456
eureka:
  client:
    # 是否注册服务,默认true.不需要对外提供服务的可配置为false
    register-with-eureka: false
    # 是否获取服务注册信息,默认true.如果不需要其它服务可配置为false
    fetch-registry: false
    service-url:
      # 服务注册中心地址,亲测可以与该服务端口一致
      defaultZone: http://192.168.1.122:8000/eureka
  instance:
    # 轮询获取服务注册信息间隔,默认30s
    lease-renewal-interval-in-seconds: 2
    # 获取服务注册持续时间,默认90s,超时获取不到会读服务缓存
    lease-expiration-duration-in-seconds: 4
  server:
    # 自我保护模式
    enable-self-preservation: false


