server:
  port: 8010
spring:
  application:
    name: company
eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://eureka:123456@192.168.1.122:8000/eureka
