server:
  port: 8020
spring:
  application:
    name: employee
eureka:
  client:
    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://192.168.1.122:8000/eureka

